CHEST_BOTTOM_HEIGHT = 145
CHEST_BOTTOM_WIDTH = 485

CHEST_TOP_HEIGHT = 187
CHEST_TOP_WIDTH = 481

COIN_WIDTH = 125
COIN_HEIGHT = 124

COIN_CHEST_RATIO = 0.8


FLAG_HEIGHT = 594
FLAG_WIDTH = 594
FLAG_CHEST_RATIO = 0.8

FLAG_INFO = {
    "width": FLAG_WIDTH,
    "height": FLAG_HEIGHT,
    "occluder_chest_ratio": FLAG_CHEST_RATIO,
}

DEFAULT_CHEST_WIDTH = 30  # vw
DEFAULT_CHEST_TOP_HEIGHT = (
    CHEST_TOP_HEIGHT / CHEST_TOP_WIDTH * DEFAULT_CHEST_WIDTH
)  # vw
LEFT_CHEST_POSITION_X = 25 - DEFAULT_CHEST_WIDTH / 2  # vw
RIGHT_CHEST_POSITION_X = 75 - DEFAULT_CHEST_WIDTH / 2  # vw
CHEST_TOP_POSITION_Y = 60  # vh
CHEST_BOTTOM_POSITION_Y = CHEST_TOP_POSITION_Y + DEFAULT_CHEST_TOP_HEIGHT  # vw

DEFAULT_COIN_WIDTH = 6  # vw
DEFAULT_COIN_HEIGHT = 6  # vw

LEFT_COIN_POSITION_X = 25 - DEFAULT_COIN_WIDTH / 2  # vw
RIGHT_COIN_POSITION_X = 75 - DEFAULT_COIN_WIDTH / 2  # vw
COIN_POSITION_Y = CHEST_BOTTOM_POSITION_Y - DEFAULT_COIN_HEIGHT / 2  # vw


COIN_INFO = {
    "width": DEFAULT_COIN_WIDTH,
    "height": DEFAULT_COIN_HEIGHT,
}
