# image dimensions in pixels
CHEST_BOTTOM_HEIGHT = 145
CHEST_BOTTOM_WIDTH = 485

CHEST_TOP_HEIGHT = 187
CHEST_TOP_WIDTH = 481

COIN_WIDTH = 125
COIN_HEIGHT = 124

FLAG_HEIGHT = 594
FLAG_WIDTH = 594

HOOK_HEIGHT = 357
HOOK_WIDTH = 456

OPEN_BAG_HEIGHT = 1113
OPEN_BAG_WIDTH = 852
CLOSED_BAG_HEIGHT = 484
CLOSED_BAG_WIDTH = 374

######################################################################
# Desired image dimensions in vw/vh, while maintaining aspect ratios
######################################################################


# CHEST
DEFAULT_CHEST_WIDTH = "35vw"  # vw
DEFAULT_CHEST_TOP_HEIGHT = (
    f"calc({CHEST_TOP_HEIGHT / CHEST_TOP_WIDTH} * {DEFAULT_CHEST_WIDTH})"  # vw
)


LEFT_CHEST_POSITION_X = f"calc(25vw - {DEFAULT_CHEST_WIDTH} / 2)"  # vw
RIGHT_CHEST_POSITION_X = f"calc(75vw - {DEFAULT_CHEST_WIDTH} / 2)"  # vw
CHEST_TOP_POSITION_Y = "50vh"  # vh
CHEST_BOTTOM_POSITION_Y = (
    f"calc({CHEST_TOP_POSITION_Y} + {DEFAULT_CHEST_TOP_HEIGHT} - 1vw)"
)


# COIN
DEFAULT_COIN_WIDTH = "5vw"  # vw
DEFAULT_COIN_HEIGHT = "5vw"  # vw

LEFT_COIN_POSITION_X = f"calc(25vw - {DEFAULT_COIN_WIDTH}/2"  # vw
RIGHT_COIN_POSITION_X = f"calc(75vw - {DEFAULT_COIN_WIDTH}/2"  # vw
COIN_POSITION_Y = (
    f"calc({CHEST_BOTTOM_POSITION_Y} - {DEFAULT_COIN_HEIGHT}/2)"  # vw
)
LEFT_COIN_POSITION_X = f"calc(25vw - {DEFAULT_COIN_WIDTH}/2)"  # vw
RIGHT_COIN_POSITION_X = f"calc(75vw - {DEFAULT_COIN_WIDTH}/2)"

COIN_INFO = {
    "width": DEFAULT_COIN_WIDTH,
    "height": DEFAULT_COIN_HEIGHT,
    "left_x": LEFT_COIN_POSITION_X,
    "right_x": RIGHT_COIN_POSITION_X,
    "y": COIN_POSITION_Y,
}


# FLAG

DEFAULT_FLAG_WIDTH = f"calc({DEFAULT_CHEST_WIDTH}*1.05)"  # vw
DEFAULT_FLAG_HEIGHT = (
    f"calc({FLAG_HEIGHT / FLAG_WIDTH} * {DEFAULT_FLAG_WIDTH})"  # vw
)
FLAG_INFO = {
    "width": DEFAULT_FLAG_WIDTH,
    "height": DEFAULT_FLAG_HEIGHT,
}
LEFT_FLAG_POSITION_X = f"calc(25vw - {DEFAULT_FLAG_WIDTH}/2)"  # vw
RIGHT_FLAG_POSITION_X = f"calc(75vw - {DEFAULT_FLAG_WIDTH}/2)"  # vw
FLAG_POSITION_Y = (
    f"calc({CHEST_TOP_POSITION_Y} - {DEFAULT_FLAG_HEIGHT}/2.5)"  # vw
)


# HOOK

DEFAULT_HOOK_WIDTH = f"30vw"  # vw
DEFAULT_HOOK_HEIGHT = (
    f"calc({HOOK_HEIGHT / HOOK_WIDTH} * {DEFAULT_HOOK_WIDTH})"  # vw
)

CHEST_HOOK_POSITION_Y = f"calc({CHEST_TOP_POSITION_Y} - {DEFAULT_HOOK_HEIGHT} + {DEFAULT_CHEST_TOP_HEIGHT}/5)"  # vw

LEFT_HOOK_POSITION_X = f"calc(25vw - 7*{DEFAULT_HOOK_WIDTH}/8)"  # vw
RIGHT_HOOK_POSITION_X = f"calc(75vw - {DEFAULT_HOOK_WIDTH}/8)"  # vw

# BAG
DEFAULT_BAG_WIDTH = f"calc({DEFAULT_CHEST_WIDTH}/2.2)"  # vw
DEFAULT_OPEN_BAG_HEIGHT = (
    f"calc({OPEN_BAG_HEIGHT / OPEN_BAG_WIDTH} * {DEFAULT_BAG_WIDTH})"  # vw
)
DEFAULT_CLOSED_BAG_HEIGHT = (
    f"calc({CLOSED_BAG_HEIGHT / CLOSED_BAG_WIDTH} * {DEFAULT_BAG_WIDTH})"  # vw
)
BAG_POSITION_Y = (
    f"calc({CHEST_BOTTOM_POSITION_Y} - {DEFAULT_OPEN_BAG_HEIGHT}/2 - 2vh)"  # vw
)
LEFT_BAG_POSITION_X = f"calc(25vw - {DEFAULT_BAG_WIDTH}/2)"  # vw
RIGHT_BAG_POSITION_X = f"calc(75vw - {DEFAULT_BAG_WIDTH}/2)"  # vw
