# image dimensions in pixels
CHEST_BOTTOM_HEIGHT = 145
CHEST_BOTTOM_WIDTH = 485

CHEST_TOP_HEIGHT = 187
CHEST_TOP_WIDTH = 481

COIN_WIDTH = 125
COIN_HEIGHT = 124

PARTIAL_OCCLUDER_HEIGHT = 594
PARTIAL_OCCLUDER_WIDTH = 594

FULL_OCCLUDER_HEIGHT = 1365
FULL_OCCLUDER_WIDTH = 2103

HOOK_HEIGHT = 357
HOOK_WIDTH = 456

OPEN_BAG_HEIGHT = 1113
OPEN_BAG_WIDTH = 852
CLOSED_BAG_HEIGHT = 484
CLOSED_BAG_WIDTH = 374

######################################################################
# Desired image dimensions in vw/vh, while maintaining aspect ratios
######################################################################


# CHEST
DEFAULT_CHEST_WIDTH = "35vw"  # vw
DEFAULT_CHEST_TOP_HEIGHT = (
    f"calc({CHEST_TOP_HEIGHT / CHEST_TOP_WIDTH} * {DEFAULT_CHEST_WIDTH})"  # vw
)


LEFT_CHEST_POSITION_X = f"calc(25vw - {DEFAULT_CHEST_WIDTH} / 2)"  # vw
RIGHT_CHEST_POSITION_X = f"calc(75vw - {DEFAULT_CHEST_WIDTH} / 2)"  # vw
CHEST_TOP_POSITION_Y = "50vh"  # vh
CHEST_BOTTOM_POSITION_Y = (
    f"calc({CHEST_TOP_POSITION_Y} + {DEFAULT_CHEST_TOP_HEIGHT} - 1vw)"
)


# COIN
DEFAULT_COIN_WIDTH = "5vw"  # vw
DEFAULT_COIN_HEIGHT = "5vw"  # vw

LEFT_COIN_POSITION_X = f"calc(25vw - {DEFAULT_COIN_WIDTH}/2"  # vw
RIGHT_COIN_POSITION_X = f"calc(75vw - {DEFAULT_COIN_WIDTH}/2"  # vw
COIN_POSITION_Y = (
    f"calc({CHEST_BOTTOM_POSITION_Y} - {DEFAULT_COIN_HEIGHT}/2)"  # vw
)
LEFT_COIN_POSITION_X = f"calc(25vw - {DEFAULT_COIN_WIDTH}/2)"  # vw
RIGHT_COIN_POSITION_X = f"calc(75vw - {DEFAULT_COIN_WIDTH}/2)"

COIN_INFO = {
    "width": DEFAULT_COIN_WIDTH,
    "height": DEFAULT_COIN_HEIGHT,
    "left_x": LEFT_COIN_POSITION_X,
    "right_x": RIGHT_COIN_POSITION_X,
    "y": COIN_POSITION_Y,
}


# PARTIAL_OCCLUDER

DEFAULT_PARTIAL_OCCLUDER_WIDTH = f"calc({DEFAULT_CHEST_WIDTH}*1.05)"  # vw
DEFAULT_PARTIAL_OCCLUDER_HEIGHT = f"calc({PARTIAL_OCCLUDER_HEIGHT / PARTIAL_OCCLUDER_WIDTH} * {DEFAULT_PARTIAL_OCCLUDER_WIDTH})"  # vw

LEFT_PARTIAL_OCCLUDER_POSITION_X = (
    f"calc(25vw - {DEFAULT_PARTIAL_OCCLUDER_WIDTH}/2)"  # vw
)
RIGHT_PARTIAL_OCCLUDER_POSITION_X = (
    f"calc(75vw - {DEFAULT_PARTIAL_OCCLUDER_WIDTH}/2)"  # vw
)
PARTIAL_OCCLUDER_POSITION_Y = f"calc({CHEST_TOP_POSITION_Y} - {DEFAULT_PARTIAL_OCCLUDER_HEIGHT}/2.5)"  # vw
PARTIAL_OCCLUDER_INFO = {
    "width": DEFAULT_PARTIAL_OCCLUDER_WIDTH,
    "height": DEFAULT_PARTIAL_OCCLUDER_HEIGHT,
    "left_x": LEFT_PARTIAL_OCCLUDER_POSITION_X,
    "right_x": RIGHT_PARTIAL_OCCLUDER_POSITION_X,
    "y": PARTIAL_OCCLUDER_POSITION_Y,
}


# FULL_OCCLUDER
DEFAULT_FULL_OCCLUDER_HEIGHT = DEFAULT_PARTIAL_OCCLUDER_HEIGHT
DEFAULT_FULL_OCCLUDER_WIDTH = f"calc({FULL_OCCLUDER_WIDTH / FULL_OCCLUDER_HEIGHT} * {DEFAULT_FULL_OCCLUDER_HEIGHT})"  # vw

LEFT_FULL_OCCLUDER_POSITION_X = (
    f"calc(25vw - {DEFAULT_FULL_OCCLUDER_WIDTH}/2)"  # vw
)
RIGHT_FULL_OCCLUDER_POSITION_X = f"calc(75vw - {DEFAULT_FULL_OCCLUDER_WIDTH}/2)"
FULL_OCCLUDER_POSITION_Y = (
    f"calc({CHEST_TOP_POSITION_Y} - {DEFAULT_FULL_OCCLUDER_HEIGHT}/2.5)"  # vw
)

FULL_OCCLUDER_INFO = {
    "width": DEFAULT_FULL_OCCLUDER_WIDTH,
    "height": DEFAULT_FULL_OCCLUDER_HEIGHT,
    "left_x": LEFT_FULL_OCCLUDER_POSITION_X,
    "right_x": RIGHT_FULL_OCCLUDER_POSITION_X,
    "y": FULL_OCCLUDER_POSITION_Y,
}

# HOOK

DEFAULT_HOOK_WIDTH = f"30vw"  # vw
DEFAULT_HOOK_HEIGHT = (
    f"calc({HOOK_HEIGHT / HOOK_WIDTH} * {DEFAULT_HOOK_WIDTH})"  # vw
)

CHEST_HOOK_POSITION_Y = f"calc({CHEST_TOP_POSITION_Y} - {DEFAULT_HOOK_HEIGHT} + {DEFAULT_CHEST_TOP_HEIGHT}/10)"  # vw

LEFT_HOOK_POSITION_X = f"calc(25vw - 7*{DEFAULT_HOOK_WIDTH}/8)"  # vw
RIGHT_HOOK_POSITION_X = f"calc(75vw - {DEFAULT_HOOK_WIDTH}/8)"  # vw

# BAG
DEFAULT_BAG_WIDTH = f"calc({DEFAULT_CHEST_WIDTH}/2.2)"  # vw
DEFAULT_OPEN_BAG_HEIGHT = (
    f"calc({OPEN_BAG_HEIGHT / OPEN_BAG_WIDTH} * {DEFAULT_BAG_WIDTH})"  # vw
)
DEFAULT_CLOSED_BAG_HEIGHT = (
    f"calc({CLOSED_BAG_HEIGHT / CLOSED_BAG_WIDTH} * {DEFAULT_BAG_WIDTH})"  # vw
)
BAG_POSITION_Y = (
    f"calc({CHEST_BOTTOM_POSITION_Y} - {DEFAULT_OPEN_BAG_HEIGHT}/2 - 2vh)"  # vw
)
LEFT_BAG_POSITION_X = f"calc(25vw - {DEFAULT_BAG_WIDTH}/2)"  # vw
RIGHT_BAG_POSITION_X = f"calc(75vw - {DEFAULT_BAG_WIDTH}/2)"  # vw

BAG_INFO = {
    "width": DEFAULT_BAG_WIDTH,
    "height": DEFAULT_OPEN_BAG_HEIGHT,
    "left_x": LEFT_BAG_POSITION_X,
    "right_x": RIGHT_BAG_POSITION_X,
    "y": BAG_POSITION_Y,
}
